initializr:
  env:
    maven:
      parent:
        artifact-id: legends-parent
        groupId: com.legends.cloud
        version: 1.1.0.SNAPSHOT
  dependencies:
    - name: legends
      content:
        - name: legends-base-starter
          id: legends-base-starter
          groupId: com.legends.cloud
          artifactId: legends-base-starter
          description: legends-base-starter spring bot、swagger and tomcat
        - name: legends-db-starter
          id: legends-db-starter
          groupId: com.legends.cloud
          artifactId: legends-db-starter
          description: legends-db-starter orm 相关
        - name: legends-cache-starter
          id: legends-cache-starter
          groupId: com.legends.cloud
          artifactId: legends-cache-starter
          description: legends-cache-starter
        - name: legends-akali-starter
          id: legends-akali-starter
          groupId: com.legends.cloud
          artifactId: legends-cache-starter
          description: 动态路由
    - name: DB
      content:
        - name: oracle(11.2.0.1.0)
          id: oracle
          groupId: com.oracle
          artifactId: ojdbc6
          description: 11.2.0.1.0
        - name: mysql
          id: mysql
          groupId: mysql
          artifactId: mysql-connector-java
          description: mysql-connector-java
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      tags:
        build: gradle
        format: project
      default: false
      action: /starter.zip
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
      default: false
  javaVersions:
    - id: 11
      default: false
    - id: 1.8
      name: 8
      default: true
  languages:
    - name: Java
      id: java
      default: true
    - name: Kotlin
      id: kotlin
      default: false
    - name: Groovy
      id: groovy
      default: false
  group-id:
    value: com.legends
  bootVersions:
    - name : Latest SNAPSHOT
      id: 1.1.3.SNAPSHOT
      default: false
    - name: 1.1.2.RELEASE
      id:  1.1.2.RELEASE
      default: true
    - name: 1.1.2.SNAPSHOT
      id:  1.1.2.SNAPSHOT
      default: false
    - name: 1.0.1.SNAPSHOT
      id: 1.0.1.SNAPSHOT
      default: false